export const cars = [
    {
        id: 1,
        name: "Mitsubishi Pajero",
        image: "/images/car_1.jpg",
        price: 3200,
        type: "suv",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "petrol",
        year: 2021,
        available: true,
    },
    {
        id: 2,
        name: "Nissan Moco",
        image: "/images/car_2.jpg",
        price: 1800,
        type: "hatchback",
        doors: 4,
        passengers: 5,
        transmission: "auto",
        fuel: "hybrid",
        year: 2022,
        available: true,
    },
    {
        id: 3,
        name: "Honda Fitta",
        image: "/images/car_3.jpg",
        price: 1500,
        type: "sedan",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "diesel",
        year: 2020,
        available: false,
    },
    {
        id: 4,
        name: "Skoda Laura",
        image: "/images/car_4.jpg",
        price: 2200,
        type: "sedan",
        doors: 6,
        passengers: 7,
        transmission: "auto",
        fuel: "petrol",
        year: 2019,
        available: false,
    },
    {
        id: 5,
        name: "Mazda LaPuta",
        image: "/images/car_5.jpg",
        price: 2700,
        type: "coupe",
        doors: 2,
        passengers: 2,
        transmission: "auto",
        fuel: "electric",
        year: 2023,
        available: true,
    },
    {
        id: 6,
        name: "Buick LaCrosse",
        image: "/images/car_6.jpg",
        price: 3500,
        type: "sedan",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "petrol",
        year: 2021,
        available: true,
    },
    {
        id: 7,
        name: "Buick LaCrosse",
        image: "/images/car_7.jpg",
        price: 4100,
        type: "suv",
        doors: 6,
        passengers: 7,
        transmission: "auto",
        fuel: "diesel",
        year: 2024,
        available: false,
    },
    {
        id: 8,
        name: "Buick LaCrosse",
        image: "/images/car_1.jpg",
        price: 2000,
        type: "hatchback",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "hybrid",
        year: 2022,
        available: true,
    },
    {
        id: 9,
        name: "Buick LaCrosse",
        image: "/images/car_2.jpg",
        price: 1700,
        type: "sedan",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "diesel",
        year: 2020,
        available: true,
    },
    {
        id: 10,
        name: "Buick LaCrosse",
        image: "/images/car_3.jpg",
        price: 4200,
        type: "coupe",
        doors: 2,
        passengers: 2,
        transmission: "auto",
        fuel: "petrol",
        year: 2023,
        available: true,
    },
    {
        id: 11,
        name: "Buick LaCrosse",
        image: "/images/car_4.jpg",
        price: 2600,
        type: "suv",
        doors: 6,
        passengers: 7,
        transmission: "auto",
        fuel: "electric",
        year: 2024,
        available: true,
    },
    {
        id: 12,
        name: "Buick LaCrosse",
        image: "/images/car_5.jpg",
        price: 3300,
        type: "sedan",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "petrol",
        year: 2021,
        available: false,
    },
    {
        id: 13,
        name: "Buick LaCrosse",
        image: "/images/car_6.jpg",
        price: 4900,
        type: "coupe",
        doors: 2,
        passengers: 2,
        transmission: "auto",
        fuel: "diesel",
        year: 2024,
        available: true,
    },
    {
        id: 14,
        name: "Buick LaCrosse",
        image: "/images/car_7.jpg",
        price: 1300,
        type: "hatchback",
        doors: 4,
        passengers: 5,
        transmission: "manual",
        fuel: "petrol",
        year: 2018,
        available: true,
    },
    {
        id: 15,
        name: "Buick LaCrosse",
        image: "/images/car_2.jpg",
        price: 3900,
        type: "suv",
        doors: 6,
        passengers: 7,
        transmission: "manual",
        fuel: "hybrid",
        year: 2022,
        available: false,
    },
];

export interface car_interface {
    id: number;
    name: string;
    image: string;
    price: number;
    type: string;
    doors: number;
    passengers: number;
    transmission: string;
    fuel: string;
    year: number;
    available: boolean;
}